import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import { TooltipProvider } from "@/components/modules/tooltip";
import { SidebarProvider } from "@/components/modules/sidebar";
import { AppSidebar } from "@/components/modules/app-sidebar";
import Navbar from "@/components/modules/navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TooltipProvider>
          <SidebarProvider>
            <AppSidebar />
            <div className="flex-1 flex flex-col">
              <Navbar />

              <main className="flex-1 p-4">{children}</main>
            </div>
          </SidebarProvider>
          <Toaster position="top-center" />
        </TooltipProvider>
      </body>
    </html>
  );
}
