// app/layout.js
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import { TooltipProvider } from "@/components/modules/tooltip";
import { MainSidebarProvider, AppSidebar } from "@/components/modules/sidebar/mainSidebar"; // تغییر اینجا
import Navbar from "@/components/modules/navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TooltipProvider>
          <MainSidebarProvider>
            <div className="flex min-h-screen"> {/* این div رو اضافه کن */}
              <AppSidebar /> {/* اینجا AppSidebar استفاده کن */}
              <div className="flex-1 flex flex-col">
                <Navbar />
                <main className="flex-1 p-4 pt-0 pl-0">{children}</main>
              </div>
            </div>
          </MainSidebarProvider>
          <Toaster position="top-center" />
        </TooltipProvider>
      </body>
    </html>
  );
}