// app/layout.js
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import { TooltipProvider } from "@/components/modules/tooltip";
import {
  MainSidebarProvider,
  AppSidebar,
} from "@/components/modules/sidebar/mainSidebar"; // تغییر اینجا
import Navbar from "@/components/modules/navbar";
import { ModalProvider } from "@/contexts/ModalContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export const viewport = {
  width: "device-width",
  initialScale: 1,
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-x-hidden`}
      >
        <TooltipProvider>
          <MainSidebarProvider>
            <ModalProvider>
              <div className="flex min-h-screen overflow-x-hidden">
                <AppSidebar />
                <div className="flex-1 flex flex-col overflow-x-hidden">
                  <Navbar />
                  <main className="flex-1 p-4 pt-0 pl-0">{children}</main>
                </div>
              </div>
            </ModalProvider>
          </MainSidebarProvider>
          <Toaster position="top-center" />
        </TooltipProvider>
      </body>
    </html>
  );
}
